import 'package:pixel_harmony/features/achievements/domain/achievement_definition.dart';

abstract final class AchievementCatalog {
  static const definitions = <AchievementDefinition>[
    AchievementDefinition(
      id: 'first_harmony',
      titleKey: 'achievementFirstHarmonyTitle',
      descriptionKey: 'achievementFirstHarmonyDescription',
      iconType: AchievementIconType.harmony,
      category: AchievementCategory.general,
      conditionType: AchievementConditionType.totalPuzzles,
      targetValue: 1,
    ),
    AchievementDefinition(
      id: 'ten_harmonies',
      titleKey: 'achievementTenHarmoniesTitle',
      descriptionKey: 'achievementTenHarmoniesDescription',
      iconType: AchievementIconType.harmony,
      category: AchievementCategory.general,
      conditionType: AchievementConditionType.totalPuzzles,
      targetValue: 10,
    ),
    AchievementDefinition(
      id: 'hundred_harmonies',
      titleKey: 'achievementHundredHarmoniesTitle',
      descriptionKey: 'achievementHundredHarmoniesDescription',
      iconType: AchievementIconType.harmony,
      category: AchievementCategory.general,
      conditionType: AchievementConditionType.totalPuzzles,
      targetValue: 100,
    ),
    AchievementDefinition(
      id: 'journey_begins',
      titleKey: 'achievementJourneyBeginsTitle',
      descriptionKey: 'achievementJourneyBeginsDescription',
      iconType: AchievementIconType.journey,
      category: AchievementCategory.journey,
      conditionType: AchievementConditionType.journeyPuzzles,
      targetValue: 10,
    ),
    AchievementDefinition(
      id: 'halfway_there',
      titleKey: 'achievementHalfwayThereTitle',
      descriptionKey: 'achievementHalfwayThereDescription',
      iconType: AchievementIconType.journey,
      category: AchievementCategory.journey,
      conditionType: AchievementConditionType.journeyPuzzles,
      targetValue: 50,
    ),
    AchievementDefinition(
      id: 'journey_complete',
      titleKey: 'achievementJourneyCompleteTitle',
      descriptionKey: 'achievementJourneyCompleteDescription',
      iconType: AchievementIconType.journey,
      category: AchievementCategory.journey,
      conditionType: AchievementConditionType.journeyPuzzles,
      targetValue: 100,
    ),
    AchievementDefinition(
      id: 'endless_explorer',
      titleKey: 'achievementEndlessExplorerTitle',
      descriptionKey: 'achievementEndlessExplorerDescription',
      iconType: AchievementIconType.endless,
      category: AchievementCategory.endless,
      conditionType: AchievementConditionType.endlessPuzzles,
      targetValue: 10,
    ),
    AchievementDefinition(
      id: 'endless_wanderer',
      titleKey: 'achievementEndlessWandererTitle',
      descriptionKey: 'achievementEndlessWandererDescription',
      iconType: AchievementIconType.endless,
      category: AchievementCategory.endless,
      conditionType: AchievementConditionType.endlessPuzzles,
      targetValue: 50,
    ),
    AchievementDefinition(
      id: 'endless_devotion',
      titleKey: 'achievementEndlessDevotionTitle',
      descriptionKey: 'achievementEndlessDevotionDescription',
      iconType: AchievementIconType.endless,
      category: AchievementCategory.endless,
      conditionType: AchievementConditionType.endlessPuzzles,
      targetValue: 100,
    ),
    AchievementDefinition(
      id: 'daily_rhythm',
      titleKey: 'achievementDailyRhythmTitle',
      descriptionKey: 'achievementDailyRhythmDescription',
      iconType: AchievementIconType.daily,
      category: AchievementCategory.daily,
      conditionType: AchievementConditionType.currentDailyStreak,
      targetValue: 7,
    ),
    AchievementDefinition(
      id: 'daily_devotion',
      titleKey: 'achievementDailyDevotionTitle',
      descriptionKey: 'achievementDailyDevotionDescription',
      iconType: AchievementIconType.daily,
      category: AchievementCategory.daily,
      conditionType: AchievementConditionType.dailyPuzzles,
      targetValue: 30,
    ),
    AchievementDefinition(
      id: 'chapter_master',
      titleKey: 'achievementChapterMasterTitle',
      descriptionKey: 'achievementChapterMasterDescription',
      iconType: AchievementIconType.chapter,
      category: AchievementCategory.journey,
      conditionType: AchievementConditionType.completedChapters,
      targetValue: 1,
    ),
    AchievementDefinition(
      id: 'perfect_journey',
      titleKey: 'achievementPerfectJourneyTitle',
      descriptionKey: 'achievementPerfectJourneyDescription',
      iconType: AchievementIconType.chapter,
      category: AchievementCategory.journey,
      conditionType: AchievementConditionType.completedChapters,
      targetValue: 10,
    ),
    AchievementDefinition(
      id: 'thousand_moves',
      titleKey: 'achievementThousandMovesTitle',
      descriptionKey: 'achievementThousandMovesDescription',
      iconType: AchievementIconType.moves,
      category: AchievementCategory.general,
      conditionType: AchievementConditionType.totalMoves,
      targetValue: 1000,
    ),
  ];

  static AchievementDefinition byId(String id) => definitions.firstWhere(
    (definition) => definition.id == id,
    orElse: () => throw ArgumentError.value(id, 'id', 'Unknown achievement.'),
  );

  static bool contains(String id) => definitions.any((item) => item.id == id);
}
