import 'dart:io';
import 'dart:math' as math;

import 'package:pixel_harmony/game/generation/generated_level.dart';
import 'package:pixel_harmony/game/generation/procedural_level_generator.dart';
import 'package:pixel_harmony/game/generation/procedural_level_request.dart';
import 'package:pixel_harmony/game/levels/level_definition.dart';

const _generator = ProceduralLevelGenerator();

void main() {
  final curated = <_CuratedCandidate>[];
  for (var number = 37; number <= 100; number++) {
    curated.add(_curate(number));
  }
  File(
    'lib/game/levels/frozen_generated_journey_levels.dart',
  ).writeAsStringSync(_render(curated));
}

_CuratedCandidate _curate(int number) {
  final boardSize = switch (number) {
    <= 70 => 4,
    _ => 5,
  };
  final difficulty = switch (number) {
    <= 50 => LevelDifficulty.medium,
    <= 70 =>
      number == 54 || number == 62 || number == 68
          ? LevelDifficulty.medium
          : LevelDifficulty.hard,
    <= 94 => LevelDifficulty.hard,
    _ => LevelDifficulty.expert,
  };
  final chapterId = switch (number) {
    <= 40 => 'sunset',
    <= 50 => 'lavender',
    <= 60 => 'aurora',
    <= 70 => 'midnight',
    <= 80 => 'blossom',
    <= 90 => 'desert',
    _ => 'northern_lights',
  };
  final targetHue = switch (chapterId) {
    'sunset' => 18.0,
    'lavender' => 278.0,
    'aurora' => number.isEven ? 178.0 : 292.0,
    'midnight' => 228.0,
    'blossom' => number.isEven ? 344.0 : 18.0,
    'desert' => 32.0,
    'northern_lights' => number.isEven ? 168.0 : 284.0,
    _ => throw StateError('Unknown chapter.'),
  };
  final seed = 1000000 + number * 104729;
  GeneratedLevel? best;
  var bestPaletteSeed = 0;
  var bestCost = double.infinity;
  for (var offset = 0; offset < 96; offset++) {
    final paletteSeed = number * 10000 + offset * 7919;
    final generated = _generator.generate(
      ProceduralLevelRequest(
        seed: seed,
        paletteSeed: paletteSeed,
        boardSize: boardSize,
        targetDifficulty: difficulty,
      ),
    );
    final hue = _averageHue(
      generated.tiles.map((tile) => tile.colorValue).toList(),
    );
    final hueDistance = _hueDistance(hue, targetHue);
    final difficultyPenalty = generated.difficulty == difficulty ? 0 : 180;
    final targetScore = switch (difficulty) {
      LevelDifficulty.medium => 43,
      LevelDifficulty.hard => 68,
      LevelDifficulty.expert => 90,
      _ => throw StateError('Unsupported authoring difficulty.'),
    };
    final scoreDistance = (generated.difficultyScore - targetScore).abs();
    final cost = hueDistance + difficultyPenalty + scoreDistance * 0.35;
    if (cost < bestCost) {
      best = generated;
      bestPaletteSeed = paletteSeed;
      bestCost = cost;
    }
  }
  if (best == null) throw StateError('No candidate for level $number.');
  return _CuratedCandidate(
    number: number,
    chapterId: chapterId,
    paletteSeed: bestPaletteSeed,
    generated: best,
  );
}

double _averageHue(List<int> colors) {
  var x = 0.0;
  var y = 0.0;
  for (final color in colors) {
    final hue = _rgbHue(color) * math.pi / 180;
    x += math.cos(hue);
    y += math.sin(hue);
  }
  final angle = math.atan2(y, x) * 180 / math.pi;
  return angle < 0 ? angle + 360 : angle;
}

double _rgbHue(int color) {
  final red = ((color >> 16) & 0xff) / 255;
  final green = ((color >> 8) & 0xff) / 255;
  final blue = (color & 0xff) / 255;
  final maximum = math.max(red, math.max(green, blue));
  final minimum = math.min(red, math.min(green, blue));
  final difference = maximum - minimum;
  if (difference == 0) return 0;
  final sector =
      maximum == red
          ? ((green - blue) / difference) % 6
          : maximum == green
          ? (blue - red) / difference + 2
          : (red - green) / difference + 4;
  final hue = sector * 60;
  return hue < 0 ? hue + 360 : hue;
}

double _hueDistance(double first, double second) {
  final direct = (first - second).abs();
  return math.min(direct, 360 - direct);
}

String _render(List<_CuratedCandidate> candidates) {
  final output =
      StringBuffer()
        ..writeln(
          '// GENERATED BY tool/freeze_journey_levels.dart. DO NOT EDIT.',
        )
        ..writeln()
        ..writeln(
          "import 'package:pixel_harmony/game/levels/journey_generated_source.dart';",
        )
        ..writeln(
          "import 'package:pixel_harmony/game/levels/level_definition.dart';",
        )
        ..writeln()
        ..writeln('const journeyGeneratedSources = <JourneyGeneratedSource>[');
  for (final candidate in candidates) {
    final generated = candidate.generated;
    output
      ..writeln('  JourneyGeneratedSource(')
      ..writeln('    journeyLevelNumber: ${candidate.number},')
      ..writeln('    generationVersion: ${generated.generationVersion},')
      ..writeln('    seed: ${generated.seed},')
      ..writeln('    boardSize: ${generated.boardSize},')
      ..writeln(
        '    targetDifficulty: LevelDifficulty.${_targetDifficulty(candidate.number).name},',
      )
      ..writeln('    paletteSeed: ${candidate.paletteSeed},')
      ..writeln("    chapterId: '${candidate.chapterId}',")
      ..writeln('  ),');
  }
  output
    ..writeln('];')
    ..writeln()
    ..writeln('final List<LevelDefinition> frozenGeneratedJourneyLevels =')
    ..writeln('    List.unmodifiable([');
  for (var index = 0; index < candidates.length; index++) {
    final candidate = candidates[index];
    final generated = candidate.generated;
    final solutionIndices = {
      for (
        var tileIndex = 0;
        tileIndex < generated.solutionTileOrder.length;
        tileIndex++
      )
        generated.solutionTileOrder[tileIndex]: tileIndex,
    };
    final initialIndices = [
      for (final id in generated.initialTileOrder) solutionIndices[id]!,
    ];
    output
      ..writeln('      _buildFrozenLevel(')
      ..writeln('        source: journeyGeneratedSources[$index],')
      ..writeln(
        '        difficulty: LevelDifficulty.${generated.difficulty.name},',
      )
      ..writeln('        difficultyScore: ${generated.difficultyScore},')
      ..writeln('        colors: const [')
      ..writeln(
        generated.tiles
            .map(
              (tile) =>
                  '          0x${tile.colorValue.toRadixString(16).padLeft(8, '0')},',
            )
            .join('\n'),
      )
      ..writeln('        ],')
      ..writeln('        initialIndices: const [${initialIndices.join(', ')}],')
      ..writeln('      ),');
  }
  output
    ..writeln('    ]);')
    ..writeln()
    ..writeln('LevelDefinition _buildFrozenLevel({')
    ..writeln('  required JourneyGeneratedSource source,')
    ..writeln('  required LevelDifficulty difficulty,')
    ..writeln('  required int difficultyScore,')
    ..writeln('  required List<int> colors,')
    ..writeln('  required List<int> initialIndices,')
    ..writeln('}) {')
    ..writeln(
      "  final id = 'level_\${source.journeyLevelNumber.toString().padLeft(3, '0')}';",
    )
    ..writeln('  final solution = List.generate(')
    ..writeln("    colors.length, (index) => '\${id}_tile_\$index',")
    ..writeln('    growable: false,')
    ..writeln('  );')
    ..writeln('  return LevelDefinition(')
    ..writeln('    id: id,')
    ..writeln('    number: source.journeyLevelNumber,')
    ..writeln("    nameKey: 'numberedLevel',")
    ..writeln('    boardSize: source.boardSize,')
    ..writeln('    difficulty: difficulty,')
    ..writeln('    difficultyScore: difficultyScore,')
    ..writeln('    tiles: List.generate(')
    ..writeln('      colors.length,')
    ..writeln('      (index) => LevelTileDefinition(')
    ..writeln("        id: '\${id}_tile_\$index',")
    ..writeln('        colorValue: colors[index],')
    ..writeln('      ),')
    ..writeln('      growable: false,')
    ..writeln('    ),')
    ..writeln(
      '    initialTileOrder: [for (final index in initialIndices) solution[index]],',
    )
    ..writeln('    solutionTileOrder: solution,')
    ..writeln('  );')
    ..writeln('}');
  return output.toString();
}

LevelDifficulty _targetDifficulty(int number) {
  if (number <= 50) return LevelDifficulty.medium;
  if (number <= 70) {
    return number == 54 || number == 62 || number == 68
        ? LevelDifficulty.medium
        : LevelDifficulty.hard;
  }
  if (number <= 94) return LevelDifficulty.hard;
  return LevelDifficulty.expert;
}

class _CuratedCandidate {
  const _CuratedCandidate({
    required this.number,
    required this.chapterId,
    required this.paletteSeed,
    required this.generated,
  });

  final int number;
  final String chapterId;
  final int paletteSeed;
  final GeneratedLevel generated;
}
